apples = (int(input())*3) + (int(input())*2) + (int(input())*1)
banana = (int(input())*3) + (int(input())*2) + (int(input())*1)
if apples == banana: print("T")
elif apples < banana: print("B")
elif apples > banana: print("A")