phrase = "Giraffe Academy"
print(phrase + "is cool")
print(phrase.lower())
print(phrase.upper())
print(phrase.islower())
print(phrase.isupper())
print(len(phrase))
print(phrase[0])
print(phrase.index("G"))
print(phrase.replace("Giraffe", "Elephant"))